name: Release

on:
  push:
    branches:
      - main
      - next
  pull_request:

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Generate one-time token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          check-latest: true
          cache: 'yarn'

      - name: Install
        run: yarn install --ignore-scripts

      - name: Build
        run: yarn build

      - name: Pack
        run: yarn zip

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
