name: Release

on:
  push:
    branches:
      - main
      - next
  pull_request:

permissions:
  contents: write

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          check-latest: true
          cache: 'yarn'

      - name: Install
        run: yarn install --ignore-scripts

      - name: Build
        run: yarn build

      - name: Pack
        run: yarn zip

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
